In [2]:
# no hace falta runearlo por ahora
# ! pip install textblob

Collecting textblob
  Downloading textblob-0.19.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: nltk>=3.9 in /opt/anaconda3/envs/deepl/lib/python3.12/site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /opt/anaconda3/envs/deepl/lib/python3.12/site-packages (from nltk>=3.9->textblob) (8.2.0)
Requirement already satisfied: joblib in /opt/anaconda3/envs/deepl/lib/python3.12/site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /opt/anaconda3/envs/deepl/lib/python3.12/site-packages (from nltk>=3.9->textblob) (2024.11.6)
Requirement already satisfied: tqdm in /opt/anaconda3/envs/deepl/lib/python3.12/site-packages (from nltk>=3.9->textblob) (4.67.1)
Downloading textblob-0.19.0-py3-none-any.whl (624 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 624.3/624.3 kB 3.0 MB/s eta 0:00:00
Installing collected packages: textblob
Successfully installed textblob-0.19.0

In [1]:
import nltk
# nltk.download('averaged_perceptron_tagger_eng')
# nltk.download('punt_tab')

import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
import re

from textblob import TextBlob
from pathlib import Path
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from tqdm import tqdm
import contractions
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk import pos_tag

In [2]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import wordnet
# Initialize stemmer/lemmatizer (run once)
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Load the dataset

In [3]:
base_path_alvaro = Path(r"C:\Users\Alvaro Millan Ruiz\OneDrive\Escritorio\BDS\Block_5\NLP\Project\TXT")
base_path_gilda = "/Users/szonjapike/Desktop/BDS/Block_5/NLP/TXT/"

base_path = base_path_gilda # change according to user

In [4]:
dataset_path_alvaro = r"C:\Users\Alvaro Millan Ruiz\OneDrive\Escritorio\BDS\Block_5\NLP\Project"
dataset_path_gilda = "/Users/szonjapike/Desktop/BDS/Block_5/NLP/Project/"

dataset_path = dataset_path_gilda # change according to user

In [26]:
# Load the dataset for sentiment analysis
df_sentiment = pd.read_csv(dataset_path + "df_sentiment_analysis.csv")
df_sentiment

,Session,Year,ISO-Code,Speech,number_sentences,number_tokens,Income Level,speeches_for_keyword_search,matched_climate_keywords,contains_climate_keyword,climate_sentences
0,45,1990,NZL,"﻿\nI should like to congratulate you, Sir, on ...",145,3512,4,i should like to congratulate you sir on your ...,"['climate change', 'greenhouse gas']",True,['but many of those be small island atoll coun...
1,45,1990,ITA,"﻿Sir, on taking the floor on behalf of the Eur...",151,4568,4,sir on take the floor on behalf of the europea...,['climate change'],True,['perhaps never in the post-war period have th...
2,45,1990,PNG,﻿On behalf of the Government and people\nof Pa...,113,2923,2,on behalf of the government and people of papu...,"['greenhouse gas', 'greenhouse effect']",True,['we be greatly concerned that in spite of omi...
3,45,1990,FIN,"﻿\nI take great pleasure in seeing you, Sir, a...",92,2080,4,i take great pleasure in see you sir a disting...,['carbon dioxide'],True,['i be think for example of policy to reduce e...
4,45,1990,DEU,"﻿I wish first of all to offer you, Mr. Preside...",292,6149,4,mr. president my warm congratulation on your e...,"['carbon dioxide', 'greenhouse effect']",True,['another key problem be the change of the wor...
...,...,...,...,...,...,...,...,...,...,...,...
3058,79,2024,CHE,Mr President\nSecretary-General\nExcellencies\...,66,1314,4,lady and gentleman on the morning of 3 march 2...,['climate change'],True,['climate change and loss of biodiversity be h...
3059,79,2024,CUB,"**Mr President,** \n**Mr Secretary-General,**...",76,2433,3,mr president * * * * mr secretary-general * * ...,"['climate change', 'global average temperature']",True,"['* * climate change be advance inexorably .',..."
3060,79,2024,CIV,Mr President of the 79th Session of the United...,41,1206,2,lady and gentleman head of state and governmen...,"['climate change', 'climate action']",True,['* mr president * * the progress achieve by o...
3061,79,2024,MKD,Distinguished President of the United Nations ...,101,2804,3,lady and gentleman be invite to address this 7...,"['climate change', 'greenhouse gas', 'climate ...",True,['6. with the alarm level of greenhouse gas em...
3062,79,2024,SGP,"Mdm President, Your Excellencies \n \n \n1 I...",100,2208,4,excellency 1 i bring you greeting from a tiny ...,['climate change'],True,['on almost every issue confront the world – f...

# Initialize sentiment analysis setup

In [48]:
from nltk.sentiment import SentimentIntensityAnalyzer
import nltk

nltk.download('vader_lexicon')
sia = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/szonjapike/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [49]:
def get_vader_scores(sent_list):
    if not isinstance(sent_list, list):
        return []
    return [sia.polarity_scores(sent) for sent in sent_list if isinstance(sent, str)]

### First try with smaller dataset

In [54]:
df_sentiment_2010_2017 = df_sentiment[df_sentiment['Year'].between(2010, 2017)].copy()
df_sentiment_2010_2017

,Session,Year,ISO-Code,Speech,number_sentences,number_tokens,Income Level,speeches_for_keyword_search,matched_climate_keywords,contains_climate_keyword,climate_sentences
906,65,2010,KOR,I would \nlike to begin by extending my warmes...,89,2102,4,i would like to begin by extend my warm congra...,['greenhouse gas'],True,['in an effort to curb greenhouse gas emission...
907,65,2010,CIV,"I would like to congratulate you, Sir, on your...",72,2464,2,i would like to congratulate you sir on your b...,"['climate change', 'kyoto protocol', 'greenhou...",True,['climate change be rightly see a a global pro...
908,65,2010,HND,\nOn behalf of the people and Government of Ho...,79,2218,2,on behalf of the people and government of hond...,"['climate change', 'greenhouse gas']",True,['we must add effort to enable foreign direct ...
909,65,2010,MKD,It is a privilege and a \ngreat honour for me ...,67,1753,3,it be a privilege and a great honour for me to...,"['climate change', 'framework convention on cl...",True,['it be a privilege and a great honour for me ...
910,65,2010,CHE,"It is a \ngreat honour for me to address, on b...",79,1444,4,it be a great honour for me to address on beha...,"['climate change', 'carbon dioxide', 'greenhou...",True,['every day we be remind of the grow and incre...
...,...,...,...,...,...,...,...,...,...,...,...
1955,72,2017,RUS,"In December of last year, the General Assembly...",99,3112,3,in december of last year the general assembly ...,['climate change'],True,['without mutual trust we can not hope for the...
1956,72,2017,DJI,"At the outset, I would like to congratulate Mr...",63,1616,2,president of the general assembly at it sevent...,['climate change'],True,['even if climate change sometimes give rise t...
1957,72,2017,GIN,"It is a great honour for me, as the current Ch...",69,1980,1,it be a great honour for me a the current chai...,['climate change'],True,['to that end the 2030 agenda the addis ababa ...
1958,72,2017,BHS,On behalf of the people and the Government of ...,90,2640,4,on behalf of the people and the government of ...,['climate change'],True,['of special concern to small island develop s...
1959,72,2017,DNK,This session of the General Assembly opens dur...,81,1887,4,this session of the general assembly open duri...,['climate change'],True,['threat and challenge such a poverty terroris...

In [55]:
import ast

# Fix stringified lists in the column
df_sentiment_2010_2017['climate_sentences'] = df_sentiment['climate_sentences'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

In [56]:
df_sentiment_2010_2017['vader_scores'] = df_sentiment_2010_2017['climate_sentences'].apply(get_vader_scores)
df_sentiment_2010_2017

,Session,Year,ISO-Code,Speech,number_sentences,number_tokens,Income Level,speeches_for_keyword_search,matched_climate_keywords,contains_climate_keyword,climate_sentences,vader_scores
906,65,2010,KOR,I would \nlike to begin by extending my warmes...,89,2102,4,i would like to begin by extend my warm congra...,['greenhouse gas'],True,[in an effort to curb greenhouse gas emission ...,"[{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compoun..."
907,65,2010,CIV,"I would like to congratulate you, Sir, on your...",72,2464,2,i would like to congratulate you sir on your b...,"['climate change', 'kyoto protocol', 'greenhou...",True,[climate change be rightly see a a global prob...,"[{'neg': 0.381, 'neu': 0.619, 'pos': 0.0, 'com..."
908,65,2010,HND,\nOn behalf of the people and Government of Ho...,79,2218,2,on behalf of the people and government of hond...,"['climate change', 'greenhouse gas']",True,[we must add effort to enable foreign direct i...,"[{'neg': 0.061, 'neu': 0.939, 'pos': 0.0, 'com..."
909,65,2010,MKD,It is a privilege and a \ngreat honour for me ...,67,1753,3,it be a privilege and a great honour for me to...,"['climate change', 'framework convention on cl...",True,[it be a privilege and a great honour for me t...,"[{'neg': 0.026, 'neu': 0.622, 'pos': 0.352, 'c..."
910,65,2010,CHE,"It is a \ngreat honour for me to address, on b...",79,1444,4,it be a great honour for me to address on beha...,"['climate change', 'carbon dioxide', 'greenhou...",True,[every day we be remind of the grow and increa...,"[{'neg': 0.203, 'neu': 0.536, 'pos': 0.261, 'c..."
...,...,...,...,...,...,...,...,...,...,...,...,...
1955,72,2017,RUS,"In December of last year, the General Assembly...",99,3112,3,in december of last year the general assembly ...,['climate change'],True,[without mutual trust we can not hope for the ...,"[{'neg': 0.087, 'neu': 0.616, 'pos': 0.296, 'c..."
1956,72,2017,DJI,"At the outset, I would like to congratulate Mr...",63,1616,2,president of the general assembly at it sevent...,['climate change'],True,[even if climate change sometimes give rise to...,"[{'neg': 0.161, 'neu': 0.839, 'pos': 0.0, 'com..."
1957,72,2017,GIN,"It is a great honour for me, as the current Ch...",69,1980,1,it be a great honour for me a the current chai...,['climate change'],True,[to that end the 2030 agenda the addis ababa p...,"[{'neg': 0.0, 'neu': 0.868, 'pos': 0.132, 'com..."
1958,72,2017,BHS,On behalf of the people and the Government of ...,90,2640,4,on behalf of the people and the government of ...,['climate change'],True,[of special concern to small island develop st...,"[{'neg': 0.312, 'neu': 0.598, 'pos': 0.09, 'co..."
1959,72,2017,DNK,This session of the General Assembly opens dur...,81,1887,4,this session of the general assembly open duri...,['climate change'],True,[threat and challenge such a poverty terrorism...,"[{'neg': 0.465, 'neu': 0.499, 'pos': 0.036, 'c..."

In [57]:
df_sentiment_2010_2017.iloc[473]['climate_sentences']

['inevitable climate change which be recognize a the great challenge of our time will decide the fate of our planet and darkens our future prospect by already threaten our present .',
 'in the light of the increase number and persistence of crisis area cause both by conflict and by natural disaster whose frequency we now associate with the rate of climate change we must take into consideration the need of over 50 million people .',
 'a the issue of climate change can not be separate from the question of the ocean the prince government will continue to defend an objective of sustainable development dedicate to healthy and productive ocean for all .']

In [58]:
df_sentiment_2010_2017.iloc[473]['vader_scores']

[{'neg': 0.074, 'neu': 0.71, 'pos': 0.216, 'compound': 0.6124},
 {'neg': 0.196, 'neu': 0.69, 'pos': 0.114, 'compound': -0.7506},
 {'neg': 0.0, 'neu': 0.926, 'pos': 0.074, 'compound': 0.4019}]